### ISSUE TITLE
{% csrf_token %} does not work within macros

### ISSUE THREAD

**Issue by jamesrobb** [niwibe/django-jinja#100]
Hello,

The problem is pretty straightforward. I have found that when I have defined macros, trying to access the csrf_token tag does not work. I have verified many times that it works outside the definiton of a macro.

Is this an actual issue or is there something I am doing incorrectly?

**Comment by niwibe** [comment]
I don't know :S, csrf_token is a standard jinja extension, And should work like any other extension.

**Comment by jamesrobb** [comment]
I have done some more testing, and it seemed that the tag for whatever reasons just doesn't work within a macro. I have to pass the value to macro when I was calling it as the solution.

**Comment by niwibe** [comment]
I have tested in in the current master and it now works as expected. I'm not really know why it does not works previously.

**Comment by brycedrennan** [comment]
I'm experiencing this on django-jinja==1.4.1 with jinja2==2.7.2

**Comment by sazl** [comment]
I experienced this issue with django-jinja==1.4.1 and Jinja2=2.8
The issue is that import does not pass the current context to the macro

http://jinja.pocoo.org/docs/dev/templates/#import-visibility

To solve the issue you must import the macro with the context

    {% import 'macro.jinja' as m with context %}
