### ISSUE TITLE
django-jinja 1.3.1 + django-pipeline

### ISSUE THREAD

**Issue by aisayko** [niwibe/django-jinja#103]
Hello,

I'm just upgraded django-jinja 1.1.0 to django-jinja 1.3.1 and got some errors with pipeline extension:

    Encountered unknown tag 'stylesheet'.

My settings for django-jinja:

    DEFAULT_JINJA2_TEMPLATE_EXTENSION = '.jinja'
    JINJA2_BYTECODE_CACHE_ENABLE = True
    JINJA2_ENVIRONMENT_OPTIONS = {
        'trim_blocks': True,
        'autoescape': True
    }

    from django_jinja.base import DEFAULT_EXTENSIONS
    JINJA2_EXTENSIONS = DEFAULT_EXTENSIONS + ['pipeline.jinja2.ext.PipelineExtension']

I've solved this issue by replace this settings as next:

    DEFAULT_JINJA2_TEMPLATE_EXTENSION = '.jinja'
    JINJA2_BYTECODE_CACHE_ENABLE = True
    JINJA2_ENVIRONMENT_OPTIONS = {
        'trim_blocks': True,
        'autoescape': True,
        'extensions': ['pipeline.jinja2.ext.PipelineExtension']
    }

Seems like there is a bug with JINJA2_EXTENSIONS setting.

Version of django-pipeline is 1.4.7

**Comment by niwibe** [comment]
Thanks for reporting it! Seems clearly a bug.

**Comment by niwibe** [comment]
This is mainly related to `from django_jinja.base import DEFAULT_EXTENSIONS` import, because it causes some circular imports. You should specify the explicit list of default extensions without importing it.

**Comment by aisayko** [comment]
Thanks!
