### ISSUE TITLE
Improve docs for Django 1.i8

### ISSUE THREAD

**Issue by SimonSteinberger** [niwibe/django-jinja#106]
I think, django-jinja is a really helpful and great addition to Django 1.8, despite basic Jinja2 support has been added to this Django version. However, I can't get it to run properly and the documentation on Django 1.8 doesn't help. Maybe you can give some hints or extend the documentation in these points:

1) Does the settings constant JINJA2_AUTOESCAPE still have any effect in Django 1.8? If not, how do you turn off autoescaping?

2) Elementary template functions are not working, and I have no idea why. E.g. translation strings {{ _(...) }} or the {{ super() }} block insertion.

3) How to make use of the Django caching system? Using "loaders" in the OPTIONS doesn't seem to work:
'loaders': [('django.template.loaders.cached.Loader', ['django_jinja.loaders.AppLoader', 'django_jinja.loaders.FileSystemLoader'])],

Maybe you could point out a bit clearer what the differences concerning Django 1.8 and lower versions are.

Any help appreciated :-)) Thanks for this great app!

**Comment by niwibe** [comment]
Hi @SimonSteinberger 

Thanks for using django-jinja. You are right, some part of the documentation is not clearly clear.
I just have pushed some time ago improvements to the docs including a complete example for django 1.8.

Independently of that, I'll try to reply all your questions:

1. No, no any django 1.7 related settings are valid for django 1.8 (if you are using django 1.8 like configuration and backend)

2. Sincerelly, without more information I can not help in this, sorry.

3. This is completely unnecesary. The django cached loaders are just for django, jinja caches the templates automatically without additional loaders. Then, the django_jinja.loaders.AppLoader will only work if you are using django < 1.7. With django 1.8 these loaders are not necesary. Summary: remove any loader specific settings if you are using django 1.8.

**Comment by SimonSteinberger** [comment]
Thanks for your quick reply. That's already helpful.

Just couldn't find any new example code. Where is it?

By the way, there's a small typo in the docs - just search for:
>> "match_extension", ".jinja" <<
It's supposed to be:
>> "match_extension": ".jinja" <<

So, I still can't see how to turn off autoescape with the new settings.

**Comment by niwibe** [comment]
Thenk you for the typo fix.

About autoescape, you can see the same example some lines below... `"autoescape": True,`

**Comment by SimonSteinberger** [comment]
I just found out how to get super() and _('...') to work. I started off with the example settings in your docs. However, they only work for me, when using django_jinja as the *first* backend and the Django DTL as second backend. So, my configuration looks roughly like this:

TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'APP_DIRS': True,
        'OPTIONS': { 'match_extension': '.jinja' },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True
    }
]

Sorry for missing white space.

**Comment by SimonSteinberger** [comment]
Since the docs are already much better with the full example configuration, I'm closing this issue.
Nonetheless, it's seems to be important to *first* list the django_jinja in the TEMPLATES setting. Otherwise Django's template engine tries to render the ".jinja" templates and fails.
