### ISSUE TITLE
Severe parsing errors?

### ISSUE THREAD

**Issue by SimonSteinberger** [niwibe/django-jinja#107]
I'm observing some strange behaviors when using Django 1.8 RC1. They look very much like parsing errors:

1) Outputting a variable that doesn't actually exist in the template's context. E.g. just writing {{ x }}, while "x" does not exist, should output nothing - or None or it should result in an error. However, it simply outputs the whole fragment "{{ x }}" as string. Same for {{ abc }} results in an output of "{{ abc }}", when there's no variable names "abc".

2) Probably related: {{ request.GET.var|e }} should output the escaped value of the request param "var". Yet, when "var" does not exist, the output should be empty or None - or error. However, this *prints* actually the error message that such a key does not exist in the query dict. That's very inconvenient and probably a but.

3) {{ request.GET.var or request.POST.var }} should either output the GET or POST param "var", or if neither exists, the output should be empty. However, if neither exists, we get to see the error message mentioned above.

There are workarounds, but it would be really great if that could be fixed. It was working fine with Django 1.7 and the previous version of django_jinja. Using workarounds makes conversions from Django's template engine to django_jinja very hard.

Thanks again for looking into this!

**Comment by SimonSteinberger** [comment]
Hi Andrey, can you point me into the right direction on what might causing this? So I can dig into it myself ... I think that's a really important issue.

**Comment by niwibe** [comment]
hi @SimonSteinberger 

This is maybe is caused with "undefined" settings. http://jinja.pocoo.org/docs/dev/api/#undefined-types
Since django-jinja 1.3 the DebugUndefined is used when django DEBUG settings is on. It is only dor debug purposes.

**Comment by SimonSteinberger** [comment]
Possibly, yes. Do you see a way to avoid the issues above? As it is, it's really problematic ...

**Comment by niwibe** [comment]
Overwritting the "undefined" parameter with a concrete class that you want to use, o put django DEBUG to False.

**Comment by SimonSteinberger** [comment]
Genius :-)) That's it - thanks!!

from jinja2 import Undefined
class NotUndefined(Undefined):
    def __unicode__(self):
        return ''

TEMPLATES = [{
        'BACKEND': 'django_jinja.backend.Jinja2',
        'OPTIONS': {
            'match_extension': '.jinja',
            'undefined': NotUndefined,
            ...
