### ISSUE TITLE
match_extension not reliably catching all Jinja2 templates

### ISSUE THREAD

**Issue by SimonSteinberger** [niwibe/django-jinja#108]
Sorry, again me :-) Using the default option ('match_extension': '.jinja') to discover Jinja2 templates sometimes fails, when also defining the Django default template engine (DTE) in settings.py. Here's a somewhat shortened configuration example:

The following configuration fails for *all* Jinja templates, because the DTE is defined first - which results in *all* templates being rendered with Django:

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates']
    },
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [BASE_DIR+'/templates'],
        'APP_DIRS': True,
        'OPTIONS': { 'match_extension': '.jinja' }
    },
]

This one works:

TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [BASE_DIR+'/templates'],
        'APP_DIRS': True,
        'OPTIONS': { 'match_extension': '.jinja' }
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates']
    },
]

However, in some rare cases, still the DTE tries to render a Jinja2 template. I wasn't able to track down the cause, but it's reproducible for certain views in my project (actually only one). Same problem with ("match_regex": "*\.jinja$",). I assume the issues are related.

**Comment by niwibe** [comment]
Yes, that is expected. As you can observe, `TEMPLATES` settings is a sorted list if backends. Django will try them in order. And as django-jinja backend works as midleware, it shoul alsways be the first or before django's backend.

**Comment by SimonSteinberger** [comment]
"4.2. Quick Setup" in the documentation need a change then.

Yet, that still doesn't fix the second issue: At least in one location, the wrong engine is chosen (in a project of mine). Couldn't narrow it down yet to a specific cause, though.

**Comment by SimonSteinberger** [comment]
Ok, got it, the second issue: I'm using a helper for adding request context to render_to_string like so:

from django.template.loader import render_to_string
def direct_to_string(request, *args, **kwargs):
    kwargs['context_instance'] = RequestContext(request)
    return render_to_string(*args, **kwargs)

When the context_instance is set, the wrong template engine is chosen by Django. No clue how to avoid this.

**Comment by SimonSteinberger** [comment]
Forget about it: The "context_instance" parameter is deprecated in Django 1.8 (and removed in Dango 2.0), anyways. Using "request=request" instead works beautifully, also with django-jinja.
