### ISSUE TITLE
{% trans %} is not parsed by makemessages in Django 1.8 RC1

### ISSUE THREAD

**Issue by SimonSteinberger** [niwibe/django-jinja#109]
All translations that use the {% trans %} template tag are not included in the PO files after makemessages was run. In fact, all existing phrases were removed from the PO file. Very unfortunate :-P

Translation of the templates works if the phrases in question are inserted manually into the PO file.

_("...") works fine, though.

**Comment by niwibe** [comment]
Do you have django_jinja in installed apps? The django `makemessages` command does not handles the jinja translations. For it django_jinja comes with own `makemessages` command that extends the django's one for work with jinja2 trans tags.

**Comment by SimonSteinberger** [comment]
Sure, it's installed correctly and typical _('...') translation strings are captured as expected. Only the {% trans ... %} strings are lost. And it's a project that's been running on django_jinja for months now - this is merely the transition to Django 1.8.

**Comment by niwibe** [comment]
Hmm, very strange, maybe django 1.8 introduces some additional changes. Ok, I'll review it ;)

**Comment by SimonSteinberger** [comment]
Thanks!

It's a pretty huge project we're transitioning - with lots and lots of code and 26 languages ... that's probably why we're detecting some issues. We're using django_jinja on Pixabay.com for every HTML template, serving over 1.5 million pages per day ;-)

**Comment by SimonSteinberger** [comment]
I just tried to rewrite all {% trans %} tags into _('...') tags and noticed, the actual problem is different than what I first reported: We use "trans" for all translations containing variables, e.g. {% trans name='foo' %}. So, that's what doesn't seem to be working properly. Also when writing the same phrases in the other form  {{ _('... %(name)s ...', name='foo') }}, makemessager doesn't find them.

Any idead or news on the issue? Would be really helpful and much, much appreciated.

**Comment by niwibe** [comment]
Hi @SimonSteinberger 

I have tested the current master version with django 1.8 and it parses all {% trans %} and {{ _("") }} perfectly, maybe you are doing something wrong?

This is a command that I have executed:

```
python manage.py makemessages -v3 -e .jinja
```

I have tested it with this template: https://github.com/niwibe/django-jinja/blob/master/testing/testapp/templates/i18n_test.jinja

**Comment by SimonSteinberger** [comment]
That's already helpful. I just tested another project, and it worked there, too. So it seems to be something wrong with just our main site. Although settings and usage of templates is the same. I'll keep digging and post as soon as I find the cause.

**Comment by SimonSteinberger** [comment]
That hint was already very helpful. And very embarrassingly I must admit a bad mistake on my part that I just tracked down: I forgot to include 'django_jinja' in INSTALLED_APPS. Surprisingly everything except this single feature worked perfectly.
