### ISSUE TITLE
documentation typo for django 1.8

### ISSUE THREAD

**Issue by przerull** [niwibe/django-jinja#115]
Hi niwibe,

This is a great library.  Thank you for your work.

I moved over do django 1.8 and noticed that in the documentation on http://niwibe.github.io/django-jinja/#_quick_setup_2 there is a typo in the sample python code for the TEMPLATE option, namely:

```python
"OPTIONS": {
    "match_extension", ".jinja",
}
```

I think you meant the comma between "match_extension", and ".jinja" to be a colon.

I notice that the [documentation code has this fix](https://github.com/niwibe/django-jinja/blame/master/doc/content.adoc#L243).

Could you please regenerate the documentation on github.io to avoid confusion from other users?

Many thanks!

**Comment by niwibe** [comment]
Done, thanks for notice me.
