### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by MikeVL** [niwibe/django-jinja#125]
I`am try to make tests with jinja templates, and assertTemplateUsed raise `AssertionError: No templates used to render the response` and response.context not contain template context variable.

```
response = self.client.get(url)
self.assertTemplateUsed(response, 'template.jinja')
```

**Comment by niwibe** [comment]
At this moment this is not supported feature.

**Comment by MikeVL** [comment]
How is to possible to get template context in tests?

**Comment by niwibe** [comment]
response.context maybe? But I'm not remember well that sorry.

**Comment by MikeVL** [comment]
O, yes, response.context.

**Comment by ipmb** [comment]
You may have some luck with:

```self.assertIn('template_name.html', response.template_name)```
