### ISSUE TITLE
mark form elements as "safe" in templates

### ISSUE THREAD

**Issue by gandriyko** [niwibe/django-jinja#71]
This not working. It's is not marked as safe.
```python
{{ formset.management_form }}
{{ form.media }}
```

Temporarily solution:
```python
{{ formset.management_form|safe }}
{{ form.media|safe }}
```

**Comment by niwibe** [comment]
I think that monkypatch every thinkg in django is very tedious, for that cases I prefer leave them as unsafe. Sorry. I will accept a pull request for fixing that but currently I dont have time for research and test that.
