### ISSUE TITLE
DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE set to r"^(?!admin/).*" causes admin logout failure

### ISSUE THREAD

**Issue by crazyyi** [niwibe/django-jinja#76]
The advanced feature of template settings 

```DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE = r"^(?!admin/).*" ```

will cause admin logout failure. 

```
Django Version:	1.7.1
Exception Type:	TemplateSyntaxError
Exception Value:	
Encountered unknown tag 'load'.
Exception Location:	/Users/yizeng/Documents/python_projects/to_pm/ENV/lib/python3.4/site-packages/jinja2/parser.py in fail, line 51
```

I have to use ```DEFAULT_JINJA2_TEMPLATE_EXTENSION = '.jinja'``` to specify template file suffix.

**Comment by salsotto** [comment]
Hello,

How can I set DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE to intercept urls "admin /" and "debug_toolbar /"?

**Comment by salsotto** [comment]
I got this way:

DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE = r"^(?!debug_toolbar|painel)/.*"

Tks a lot for this app!
