### ISSUE TITLE
Filters breaks autoescape

### ISSUE THREAD

**Issue by BooBSD** [niwibe/django-jinja#78]
Hello,

It seems, filters break autoescape. Following code is not escaped `<script>alert("Hello!")</script>`:

`{{ product.description|linebreaksbr }}`

Also filter `escape` does not work:

`{{ product.description|linebreaksbr|escape }}`

My settings:

```
TEMPLATE_LOADERS = (
    'django_jinja.loaders.FileSystemLoader',
    'django_jinja.loaders.AppLoader',
)
DEFAULT_JINJA2_TEMPLATE_EXTENSION = '.jinja'
JINJA2_BYTECODE_CACHE_ENABLE = True
JINJA2_ENVIRONMENT_OPTIONS = {
    'trim_blocks': True,
    'autoescape': True,
}
JINJA2_EXTENSIONS = ['pipeline.jinja2.ext.PipelineExtension']
```

**Comment by niwibe** [comment]
Now is fixed in master, is happens becuase it is django filter and its behavior not fits properly to jinja2 one.

**Comment by BooBSD** [comment]
Thank you!
