### ISSUE TITLE
Bug with pipeline PIPELINE_CSS, extra_context > media

### ISSUE THREAD

**Issue by samuelcolvin** [niwibe/django-jinja#79]
If I specify:

```
PIPELINE_CSS = {
    'bootstrap': {
        'source_filenames': ('libs/css/bootstrap.css',),
        'output_filename': 'css/bootstrap.css',
        'extra_context': {'media': 'all'},
    },
}
```

Then:

    {{ compressed_css('bootstrap') }} --> <link href="/static/libs/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />

(which is fine).

But if I specify:
```
PIPELINE_CSS = {
    'bootstrap': {
        'source_filenames': ('libs/css/bootstrap.css',),
        'output_filename': 'css/bootstrap.css',
    },
}
```

Then:

    {{ compressed_css('bootstrap') }} --> <link href="/static/libs/css/bootstrap.css" rel="stylesheet" type="text/css" media="&lt;function media at 0x7f2d7dfac140&gt;" />

[According to pipeline docs](http://django-pipeline.readthedocs.org/en/latest/configuration.html#extra-context) the default for media should be `"all"`.

Looks like the function simply isn't being evaluated?

**Comment by niwibe** [comment]
Yes, it happens because django template evaluate functions like variables maybe. I'll try to fix it.

**Comment by niwibe** [comment]
Hmm. I can not reproduce that behavior. I add some tests for it, and when media is not specified, media attribute will not redered. 

However, pipeline docs are completely wrong, If you see the source code of pipeline, bot, the template tags and templatefilters omit the media attribute rendering if is not specified.

**Comment by niwibe** [comment]
What version you are using of pipeline?

**Comment by samuelcolvin** [comment]
sorry I never got back to you `django-pipeline==1.4.3`

**Comment by niwibe** [comment]
In my tests everything works as expected :s 

In any case the builtin helpers for pipeline are now deprecated in favor to the native django-pipeline jinja extension that you can use with django-jinja.
