### ISSUE TITLE
load_template fails with django.test.Client

### ISSUE THREAD

**Issue by suutari-ai** [niwibe/django-jinja#82]
We have a test case that is trying to do a GET-request with `django.test.Client` for a page that is rendered with a Jinja template. The test fails in `LoaderMixin.load_template` while doing
```
template = env.get_template(template_name)
```
(in [loaders.py:35](https://github.com/niwibe/django-jinja/blob/1.1.0/django_jinja/loaders.py#L35)) because `env` is None.

Versions in use:
 * Python 3.4.0
 * Django 1.7.1
 * django-jinja 1.1.0

Backtrace:

```
tests/front/test_xxxxxx.py:16: in test_get_index
    response = client.get(path='/')
django/test/client.py:470: in get
    **extra)
django/test/client.py:286: in get
    return self.generic('GET', path, secure=secure, **r)
django/test/client.py:358: in generic
    return self.request(**r)
django/test/client.py:440: in request
    six.reraise(*exc_info)
django/utils/six.py:550: in reraise
    raise value
django/core/handlers/base.py:137: in get_response
    response = response.render()
django/template/response.py:103: in render
    self.content = self.rendered_content
django/template/response.py:78: in rendered_content
    template = self.resolve_template(self.template_name)
django/template/response.py:54: in resolve_template
    return loader.select_template(template)
django/template/loader.py:188: in select_template
    return get_template(template_name, dirs)
django/template/loader.py:144: in get_template
    template, origin = find_template(template_name, dirs)
django/template/loader.py:132: in find_template
    source, display_name = loader(name, dirs)
django/template/loader.py:44: in __call__
    return self.load_template(template_name, template_dirs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django_jinja.loaders.FileSystemLoader object at 0x7f92b4618550>
template_name = 'shoop/index.jinja', template_dirs = None

    def load_template(self, template_name, template_dirs=None):
        if self.match_template(template_name):
            try:
>               template = env.get_template(template_name)
E               AttributeError: 'NoneType' object has no attribute 'get_template'

django_jinja/loaders.py:35: AttributeError
```

**Comment by niwibe** [comment]
I see that you are using py.test. In that case, only for discard external factors, are you have something like this:

```python
def pytest_configure(config):
    import django
    django.setup()
```
on conftest.py on your tests directory.

With django 1.7 is strictly important call this function, because it launches all application lifecycle hooks.

**Comment by suutari-ai** [comment]
OK, I added that conftest.py, but it didn't help.

So then I added the following to conftest.py:
```python
def pytest_configure(config):
    import django
    import django_jinja.base
    print(django_jinja.base.env)
    django.setup()
    print(django_jinja.base.env)            
    django_jinja.base.setup_django_lte_17()
    print(django_jinja.base.env)
```

This printed
```
None
None
<jinja2.environment.Environment object at 0x7f20b6aa90f0>
```
I.e. only the last call initialized `django_jinja.base.env`. Then of course the tests worked too, but if I understood correctly the `django.setup()` call should have been enough. Right?

**Comment by niwibe** [comment]
Yes, calling django.setup() should be enought because, is a django way to launch the application registry, you can read about it here: https://docs.djangoproject.com/en/1.7/ref/applications/#django.setup

django_jinja, uses the native supported method of each django version for setup properly the environment, and in case of django >= 1.7 it uses the application ready hook: https://github.com/niwibe/django-jinja/blob/master/django_jinja/apps.py

If you try to run the setup_django_lte_17 before setup(), and it surely raises an exception that application registry is not ready. 

I don't know why in your case, it not works. Are you have a "django_jinja" in INSTALLED_APPS ?

**Comment by suutari-ai** [comment]
OK, that was my problem. "django_jinja" was not in INSTALLED_APPS of the test configuration.

Sorry, for wasting your time and thanks for your help!
