### ISSUE TITLE
Trans tag destroy national characters

### ISSUE THREAD

**Issue by martinsvoboda** [niwibe/django-jinja#84]
If I call django makemessages command, output from trans tag and underscope function is different. String from trans tag is saved to .po file in different charset (not in UTF-8). I use python 3.4.2 on 64bit Windows 7.

.\templates\test.html
```jinja
{% trans name=user.name %}
    ěščřžýáíé {{ name }}
{% endtrans %}

{{ _('ěščřžýáíé %(name)s')|format(name=user.name) }}
```

.\LC_MESSAGES\django.po
```
#: .\templates\test.html:8
#, python-format
msgid ""
"\n"
"    ěščřžýá�xadé %(name)s\n"
msgstr ""

#: .\templates\test.html:13
#, python-format
msgid "ěščřžýáíé %(name)s"
msgstr ""
```

**Comment by niwibe** [comment]
This seems to be not django-jinja bug, because the makemessages command implementation is django's one, the django-jinja's version inherits all code from django and overwrites the regular expresion for jinja version of trans.
