### ISSUE TITLE
Recommend using the global namespace instead of "context processors"

### ISSUE THREAD

**Issue by aaugustin** [niwibe/django-jinja#91]
The documentation advertises support for "context processors" as an advantage over Django's native Jinja2 backend.

I believe that's an anti-feature. Context processors are a poor API. Jinja2's [global namespace](http://jinja.pocoo.org/docs/dev/api/#the-global-namespace) is a superior replacement.

Most built-in context processors don't depend on the request in practice and many return a constant. There's no reason to make a function call and pass the request object in that case.

I understand that the goal of django-jinja is to make jinja2 look like the Django Template Language. That requires recreating some mistakes that Django made and Jinja fixed. Nonetheless I would suggest pointing to the better solution in the documentation, in that case, the global namespace.

**Comment by niwibe** [comment]
Thanks for the suggestion, I'll add this to the documentation! 
I'll keep it open until fixes.

Thanks again.

**Comment by niwibe** [comment]
This is already added in the documentation.
