### ISSUE TITLE
django 1.8 support

### ISSUE THREAD

**Issue by amitu** [niwibe/django-jinja#92]
Current django-jinja is not compatible with django-1.8.

It [refers](https://github.com/niwibe/django-jinja/blob/master/django_jinja/base.py#L297) `app_directories.app_template_dirs`, which has been [removed](https://github.com/django/django/commit/d58597a7b8b47add828c9418cdf48299e3b8f5bb#diff-6650649b07e8476415718effff1d57afL36) from `app_directories` module. 

Something like this should be used:

```
from django.template.utils import get_app_template_dirs
get_app_template_dirs('templates')
```

**Comment by niwibe** [comment]
Hi @amitu 
The django 1.8 support is already implemented, using django 1.8 native multiple template engine support recentrly introduced. If you can see, the tests passes with django 1.8 https://travis-ci.org/niwibe/django-jinja/builds/51515108

You are trying use django-jinja in a "django <= 1.7 way with django 1.8 maybe?

**Comment by amitu** [comment]
I am a little unfamiliar with "django <= 1.7 way" vs "django 1.8 way". I am using coffin, it seems it is not compatible. I think coffin is using it in wrong way. I am not really sure, what I do know is my project, importd is not working with django 1.8a and these are the issues I could find.

**Comment by niwibe** [comment]
Hmm, but this project is django-jinja, is not a coffin repository... :S 

This is a documentation about changes introduced in django 1.8
https://docs.djangoproject.com/en/dev/ref/templates/upgrading/

And this are instructions for setup django-jinja with django 1.8
 http://niwibe.github.io/django-jinja/#_configure_for_django_1_8

But take care, django-jinja is not coffin and is not a direct replacement for coffin ;)

**Comment by amitu** [comment]
I think I realise my mistake. :-)
