### ISSUE TITLE
Adding custom Jinja2 extensions?

### ISSUE THREAD

**Issue by abhabongse** [niwibe/django-jinja#95]
I tried to add custom Jinja2 extensions to my project (with django 1.7) but I'm not exactly sure how to do this. I came across `settings.JINJA2_EXTENSIONS` when I looked at the source of `django_jinja.base` and thought I might be able to use it to add custom extensions.

Is this a recommended/intended way to do it? Or is there a better way to do it, maybe directly in `jinja2` module? There seems to be no documentation about `settings.JINJA2_EXTENSIONS` except when `django-pipeline` is mentioned in the documentation.

Thanks,

**Comment by niwibe** [comment]
Yes, is a documentation bug, settings.JINJA2_EXTENSIONS should be used for set additional extensions.
