### ISSUE TITLE
Django 1.9 deprecation warning

### ISSUE THREAD

**Issue by linkleonard** [niwibe/django-jinja#96]
After upgrading from Django 1.7 to Django 1.8, and changing my settings file for the 1.8 django-jinja integration, I get the following warning. I'm running on Python 3.4.

```
(medpilot-2)leonard@ubuntu ~> python manage.py shell
.../lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)
```

The warning can be attributed to the following line:
https://github.com/niwibe/django-jinja/blob/3d6ecfef493d3fdaed3cab8a2ba198899d253622/django_jinja/base.py#L12

Since django-jinja officially supports >= python 2.7, it should be safe to change it into the following:
```python
from importlib import import_module
```
... as django utils uses it for python versions < 2.7. https://docs.djangoproject.com/en/1.7/releases/1.7/#django-utils-dictconfig-django-utils-importlib

Thoughts?

**Comment by niwibe** [comment]
Yo are right! I will remove it in the next version! 

Thanks!
