### ISSUE TITLE
Missing possibility to use custom Undefined subclass

### ISSUE THREAD

**Issue by sleamey** [niwibe/django-jinja#97]
make_env function unconditionally ignores and overwrites the 'undefined' attribute in JINJA2_ENVIRONMENT_OPTIONS. So its impossible to use 'Undefined' subclasses other than 'Undefined' itself or 'DebugUndefined'

```python
 if settings.DEBUG:
        initial_params["undefined"] = jinja2.DebugUndefined
    else:
        initial_params["undefined"] = jinja2.Undefined
```

So I suppose there should be some test if 'undefined' is already in initial_params.

**Comment by niwibe** [comment]
Thanks for your suggestion. I will fix it the next version.
