### ISSUE TITLE
Document JINJA2_LOADER

### ISSUE THREAD

**Issue by phalt** [niwibe/django-jinja#99]
You've accepted a pull request for a new setting - `JINJA2_LOADER` [in this pull request](https://github.com/niwibe/django-jinja/issues/47).

However it has not be documented. Was quite a surprised when I came across it in the code!

**Comment by niwibe** [comment]
Yes, you are right.

Thank you very much for report it ;)

**Comment by niwibe** [comment]
I have documented it for django < 1.7 setups.
